[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
evm_version="paris"
optimizer = true
optimizer_rounds = 200
fs_permissions = [{ access = "read", path = "./broadcast" }]
gas_reports = ["Queens"]


# --chains--
[rpc_endpoints]
bsc = "${RPC_BSC_MAIN}"
bsctest = "${RPC_BSC_TEST}"
base = "${RPC_BASE_MAIN}"
baseSepolia = "${RPC_BASE_TEST}"

localhost = "${RPC_LOCALHOST}"


# --scans--
[etherscan]
bsc = { key = "${BSCSCAN_KEY}", chain = "56" }
bsctest = { key = "${BSCSCAN_KEY}", chain = "97" }
base = { key = "${BASESCAN_KEY}", chain = "8453"}
baseSepolia = { key = "${BASESCAN_SEPOLIA_KEY}", chain = "84532", url = "https://base-sepolia.blockscout.com/api" }

[fuzz]
runs = 100
max_test_rejects=50000

[invariant]
fail_on_revert=true